export const ERRORS_DEFINED = {
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  OTP_REQUIRED: 'OTP_REQUIRED'
};

export const AUTH_CONSTANTS = {
  TIME_TO_ASK_OTP_MAINTEIN_SESSION: 432_000_000,
  TIME_TO_ASK_OTP: 86_400_000
};
